#ifndef INCLUDE_ERROR_H_
#define INCLUDE_ERROR_H_

typedef enum {
	ERR_OK=0,
    ERR_PRN_PLUG,
    ERR_PRN_OFFLINE,
    ERR_PRN_ERROR_UR,
    ERR_PRN_ERROR_R,
    ERR_PRN_CUTTER,
    ERR_PRN_NO_PAPER,
    ERR_PRN_COVER,
	ERR_PRN_BUSY,
	ERR_PRN_DATA,

	ERR_USB_INIT=10,
	ERR_USB_NO_DEVICE_LIST,
	ERR_USB_OPEN,
	ERR_USB_DETACH,
	ERR_USB_SET_CONFIGURATION,
	ERR_USB_CLAIMING,

} errcode_t;

#endif /* INCLUDE_ERROR_H_ */
